<script>
  import Home from '@lucide/svelte/icons/house';
  import Folder from '@lucide/svelte/icons/folder';
  import Chart from '@lucide/svelte/icons/chart-column';
  import Bell from '@lucide/svelte/icons/bell';
  import Sliders from '@lucide/svelte/icons/sliders-horizontal';
  import Shield from '@lucide/svelte/icons/shield-check';
  import Plus from '@lucide/svelte/icons/plus';
  import Search from '@lucide/svelte/icons/search';
  import Sun from '@lucide/svelte/icons/sun';
  import Moon from '@lucide/svelte/icons/moon';
  import Logout from '@lucide/svelte/icons/log-out';
  import Check from '@lucide/svelte/icons/circle-check';
  import Tick from '@lucide/svelte/icons/check';
  import Clock from '@lucide/svelte/icons/clock';
  import Calendar from '@lucide/svelte/icons/calendar-days';
  import List from '@lucide/svelte/icons/list-checks';
  import Kanban from '@lucide/svelte/icons/square-kanban';
  import Users from '@lucide/svelte/icons/users';
  import Clip from '@lucide/svelte/icons/paperclip';
  import Message from '@lucide/svelte/icons/message-square';
  import Alert from '@lucide/svelte/icons/triangle-alert';
  import Trend from '@lucide/svelte/icons/trending-up';
  import Download from '@lucide/svelte/icons/download';
  import Menu from '@lucide/svelte/icons/menu';
  import Send from '@lucide/svelte/icons/send';
  import Layers from '@lucide/svelte/icons/layers';
  import Zap from '@lucide/svelte/icons/zap';
  import X from '@lucide/svelte/icons/x';
  import Help from '@lucide/svelte/icons/circle-question-mark';
  import Target from '@lucide/svelte/icons/target';
  import Flag from '@lucide/svelte/icons/flag';
  import Archive from '@lucide/svelte/icons/archive';
  import Lock from '@lucide/svelte/icons/lock';
  import Key from '@lucide/svelte/icons/key-round';
  import Device from '@lucide/svelte/icons/smartphone';
  import Trash from '@lucide/svelte/icons/trash';
  import Edit from '@lucide/svelte/icons/pencil';
  import Link from '@lucide/svelte/icons/link';
  import Grid from '@lucide/svelte/icons/layout-grid';
  import Play from '@lucide/svelte/icons/play';
  import Stop from '@lucide/svelte/icons/square';
  import Sparkles from '@lucide/svelte/icons/sparkles';
  import Inbox from '@lucide/svelte/icons/inbox';
  import Party from '@lucide/svelte/icons/party-popper';
  import Ban from '@lucide/svelte/icons/ban';
  import Command from '@lucide/svelte/icons/command';
  import Rocket from '@lucide/svelte/icons/rocket';
  import Briefcase from '@lucide/svelte/icons/briefcase';
  import Globe from '@lucide/svelte/icons/globe';
  import Cart from '@lucide/svelte/icons/shopping-cart';
  import Palette from '@lucide/svelte/icons/palette';
  import Bulb from '@lucide/svelte/icons/lightbulb';
  import Wrench from '@lucide/svelte/icons/wrench';
  import Phone from '@lucide/svelte/icons/smartphone';
  import ArrowRight from '@lucide/svelte/icons/arrow-right';
  import ArrowLeft from '@lucide/svelte/icons/arrow-left';
  import ChevL from '@lucide/svelte/icons/chevron-left';
  import ChevR from '@lucide/svelte/icons/chevron-right';
  import ChevD from '@lucide/svelte/icons/chevron-down';
  import Copy from '@lucide/svelte/icons/copy';
  import Bot from '@lucide/svelte/icons/bot';
  import Tag from '@lucide/svelte/icons/tag';
  import Timer from '@lucide/svelte/icons/timer';
  import UserPlus from '@lucide/svelte/icons/user-plus';
  import FileText from '@lucide/svelte/icons/file-text';
  import Info from '@lucide/svelte/icons/info';
  import Star from '@lucide/svelte/icons/star';
  import Bookmark from '@lucide/svelte/icons/bookmark';
  import Activity from '@lucide/svelte/icons/activity';
  import Gauge from '@lucide/svelte/icons/gauge';
  import Eye from '@lucide/svelte/icons/eye';
  import Refresh from '@lucide/svelte/icons/refresh-cw';
  import Grip from '@lucide/svelte/icons/grip-vertical';
  import Dashboard from '@lucide/svelte/icons/layout-dashboard';
  import Save from '@lucide/svelte/icons/save';
  import Circle from '@lucide/svelte/icons/circle';

  const MAP = { home: Home, folder: Folder, chart: Chart, bell: Bell, sliders: Sliders, shield: Shield, plus: Plus, search: Search, sun: Sun, moon: Moon, logout: Logout, check: Check, tick: Tick, clock: Clock, calendar: Calendar, list: List, kanban: Kanban, users: Users, clip: Clip, message: Message, alert: Alert, trend: Trend, download: Download, menu: Menu, send: Send, layers: Layers, zap: Zap, x: X, help: Help, target: Target, flag: Flag, archive: Archive, lock: Lock, key: Key, device: Device, trash: Trash, edit: Edit, link: Link, grid: Grid, play: Play, stop: Stop, sparkles: Sparkles, inbox: Inbox, party: Party, ban: Ban, command: Command, rocket: Rocket, briefcase: Briefcase, globe: Globe, cart: Cart, palette: Palette, bulb: Bulb, wrench: Wrench, phone: Phone, 'arrow-right': ArrowRight, 'arrow-left': ArrowLeft, 'chev-left': ChevL, 'chev-right': ChevR, 'chev-down': ChevD, copy: Copy, bot: Bot, tag: Tag, timer: Timer, 'user-plus': UserPlus, 'file-text': FileText, info: Info, star: Star, bookmark: Bookmark, activity: Activity, gauge: Gauge, eye: Eye, refresh: Refresh, grip: Grip, dashboard: Dashboard, save: Save, circle: Circle };

  let { name, size = 18, stroke = 1.75, class: cls = '' } = $props();
  const C = $derived(MAP[name] ?? Folder);
</script>

<C {size} strokeWidth={stroke} class="shrink-0 {cls}" aria-hidden="true" />
